import os

TELEGRAM_BOT_AUTH = os.environ['TELEGRAM_BOT_AUTH']
TELEGRAM_BOT_CHANNEL_ID = os.environ['TELEGRAM_BOT_CHANNEL_ID']
TELEGRAM_MIN_FILE_SIZE_MB = os.environ.get('TELEGRAM_MIN_FILE_SIZE_MB', 10)
TELEGRAM_MIN_FILE_SIZE_BYTES = int(TELEGRAM_MIN_FILE_SIZE_MB) * 1024 ** 2
