name: pogost-telegram-bot
base: core18
version: '1.0'
summary: Simplified telegram bot
description: |
  This are scripts to send data from our server to our telegram channel.

grade: stable
confinement: strict

parts:
  python-telegram-bot:
    # See 'snapcraft plugins'
    plugin: python
    python-version: python3
    requirements: ['requirements.txt']
    source: .

apps:
  send-image:
    command: bin/send-image
  send-video:
    command: bin/send-video
  send-video-preview:
    command: bin/send-video-preview
  send-validated-video-preview:
    command: bin/send-validated-video-preview