name: motion-telegram-bot
base: core18
version: '1.1'
summary: Simplified telegram bot
description: |
  This are scripts to send data from our server to our telegram channel.

architectures:
  - build-on: [amd64]
    run-on: [amd64]

grade: stable
confinement: strict

parts:
  python-telegram-bot:
    # See 'snapcraft plugins'
    plugin: python
    python-version: python3
    requirements: ['requirements.txt']
    source: .

apps:
  send-image:
    command: bin/send-image
    plugs: [ network ]
  send-message:
    command: bin/send-message
    plugs: [ network ]
  send-video:
    command: bin/send-video
    plugs: [ network ]
  send-video-preview:
    command: bin/send-video-preview
    plugs: [ network ]
  send-validated-video-preview:
    command: bin/send-validated-video-preview
    plugs: [ network ]
